spring.application.name=Help-desk-backend

# ======================
# Active Profile
# ======================
spring.profiles.active=local

# ======================
# Database Configuration
# ======================
#spring.datasource.url=jdbc:postgresql://localhost:5432/SpringAi
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / Hibernate
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ======================
# Groq Tool
# ======================

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# ======================
# Chat Memory
# ======================
spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

# =================
#   OLLAMA
# =================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.vectorstore.pgvector.initialize-schema=true

# Enable this when Postgres/PGVector and Ollama are running and you want to load PDFs into the vector store.
helpdesk.rag.ingestion.enabled=false
